<a href="https://colab.research.google.com/github/atikhasan007/DeepLearning/blob/main/pytorch/17_saving%20and%20Loading.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn
### complete model ###
torch.save(arg, PATH)

# model class must be defined somewhere
torch.load(PATH)
model.eval()






In [ ]:
# PyTorch-এ model-এর শুধু learned parameters (weights & biases)
# save এবং load করার জন্য ব্যবহার করা হয়।

### state dict ###
# state_dict() হলো একটি Python dictionary
# যেখানে model-এর সব trainable parameters থাকে
torch.save(model.state_dict(), PATH)

# model must be create again with parameters
model = Model(*args, **kwargs)
model.load_state_dict(torch.load(PATH))
model.eval()

In [3]:
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, n_input_features):
    super(Model, self).__init__()
    self.linear = nn.Linear(n_input_features, 1)

  def forward(self, x):
    y_pred = torch.sigmoid(self.linear(x))
    return y_pred


model = Model(n_input_features=6)
# train your model


Lazy method

In [6]:
FILE = "model.pth"
torch.save(model, FILE)
model = torch.load(FILE, weights_only=False)
model.eval()

for param in model.parameters():
  print(param)

Parameter containing:
tensor([[-0.3331,  0.2811, -0.2652,  0.3472, -0.1159, -0.1219]],
       requires_grad=True)
Parameter containing:
tensor([0.2465], requires_grad=True)


recommended method

In [8]:
FILE = "model.pth"
torch.save(model.state_dict(), FILE)
# model = torch.load(FILE, weights_only=False)
# model.eval()
loaded_model = Model(n_input_features=6)
loaded_model.load_state_dict(torch.load(FILE))
loaded_model.eval()


for param in loaded_model.parameters():
  print(param)

Parameter containing:
tensor([[-0.3331,  0.2811, -0.2652,  0.3472, -0.1159, -0.1219]],
       requires_grad=True)
Parameter containing:
tensor([0.2465], requires_grad=True)


In [10]:
print(model.state_dict())

OrderedDict({'linear.weight': tensor([[-0.3331,  0.2811, -0.2652,  0.3472, -0.1159, -0.1219]]), 'linear.bias': tensor([0.2465])})


In [11]:
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
print(optimizer.state_dict())

{'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'fused': None, 'params': [0, 1]}]}


In [12]:
checkpoint = {
    "epoch": 90,
    "model_state": model.state_dict(),
    "optim_state": optimizer.state_dict()
}
torch.save(checkpoint, "checkpoint.pth")




In [13]:
loaded_checkpoint = torch.load('checkpoint.pth')
epoch = loaded_checkpoint['epoch']

model = Model(n_input_features=6)
optimizer = torch.optim.SGD(model.parameters(), lr=0)

model.load_state_dict(checkpoint['model_state'])
optimizer.load_state_dict(checkpoint['optim_state'])

print(optimizer.state_dict())

{'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'fused': None, 'params': [0, 1]}]}


gpu

In [ ]:
import torch
import torch.nn as nn

# save on gpu , load on cpu
device = torch.device("cuda")
model.to(device)
torch.save(model.state_dict(), PATH)

device = torch.device("cpu")
model = Model(*args, **Kwargs)
model.load_state_dict(torch.load(PATH, map_location=device))


In [ ]:
# save on gpu , load on gpu
device = torch.device("cuda")
model.to(device)
torch.save(model.state_dict(), PATH)

model = Model(*args, **kwargs)
model.load_state_dict(torch.load(PATH))
model.to(device)

In [ ]:
# save on cpu, load on gpu
torch.save(model.state_dict(), PATH)

device = torch.device("cuda")
model = Model(*args, **kwargs)
model.load_state_dict(torch.load(PATH, map_location="cuda:0")) # Choose whatever GPU device number
model.to(device)