<a href="https://colab.research.google.com/github/atikhasan007/DeepLearning/blob/main/pytorch/autograd_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


*PyTorch এ autograd এর কাজ হলো automatic differentiation করা, অর্থাৎ automatically gradient calculate করা।*





1. Operations track করে

যে tensor এ requires_grad=True থাকে, তার সব calculation graph আকারে save হয়।

2. Gradient calculate করে

backward() call করলে chain rule ব্যবহার করে gradient বের করে।

3. Neural Network train করতে সাহায্য করে

Training এর সময়:

* Forward pass
* Loss calculate
* Backpropagation
* Weight update

এই পুরো process এ autograd gradient দেয়।

In [2]:
# rand range [0 -> 1] , Uniform  distribution
# randn range [-enfinity , +enfinity] mean = 0 , std = 1

* rand() → random initialization, probability, dropout mask
* randn() → neural network weight initialization (সবচেয়ে common)

In [3]:
import torch

x = torch.randn(3, requires_grad=True)
print(x)

tensor([-0.7409,  0.2332,  0.1160], requires_grad=True)


In [4]:
y = x + 2


In [5]:
print(y)

tensor([1.2591, 2.2332, 2.1160], grad_fn=<AddBackward0>)


In [6]:
z = y*y*2
print(z)

tensor([3.1709, 9.9741, 8.9550], grad_fn=<MulBackward0>)


In [7]:
z = z.mean()
print(z)

tensor(7.3667, grad_fn=<MeanBackward0>)


In [8]:
z.backward() # dz / dx
print(x.grad)

tensor([1.6789, 2.9776, 2.8213])


In [9]:
 # x.requires_grad(False)   “এই tensor-এর জন্য gradient হিসাব করো না
 # x.detach() এটা tensor-কে পুরো computation graph থেকে আলাদা করে দেয়
 # with torch.no_grad():এটা একটা context manager, যার ভিতরে সব gradient tracking বন্ধ

In [11]:
x.requires_grad_(True)

tensor([-0.7409,  0.2332,  0.1160], requires_grad=True)

In [10]:
x.requires_grad_(False)
print(x)

tensor([-0.7409,  0.2332,  0.1160])


In [12]:
y = x.detach()
print(y)

tensor([-0.7409,  0.2332,  0.1160])


In [14]:
y = x + 2
print(y)

tensor([1.2591, 2.2332, 2.1160], grad_fn=<AddBackward0>)


In [13]:
with torch.no_grad():
  y = x + 2
  print(y)

tensor([1.2591, 2.2332, 2.1160])


# **Training Example**

In [17]:
import torch

weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
  model_output = (weights * 3).sum()

  model_output.backward()

  print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [19]:
# empty gradient

import torch

weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
  model_output = (weights * 3).sum()

  model_output.backward()

  print(weights.grad)
  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


# **Optimization**

In [21]:
import torch

weights = torch.ones(4, requires_grad=True)
optimizer = torch.optim.SGD([weights], lr=0.01) # weights should be in a list
optimizer.step()
optimizer.zero_grad()