<a href="https://colab.research.google.com/github/atikhasan007/DeepLearning/blob/main/pytorch/pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import torch


In [18]:
x = torch.empty(3)
print(x)

tensor([3.6022e-12, 7.1223e+28, 3.0958e-18])


In [19]:
x = torch.empty(2,2, 3)
print(x)

tensor([[[9.5812e-32, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 4.3324e-41]],

        [[1.3593e-43, 0.0000e+00, 1.5331e-35],
         [0.0000e+00, 5.8932e-32, 0.0000e+00]]])


In [20]:
x = torch.zeros(3)
print(x)

tensor([0., 0., 0.])


In [21]:
x = torch.rand(2,3)
print(x)

tensor([[0.1499, 0.7092, 0.0999],
        [0.7893, 0.2294, 0.1133]])


In [22]:
x = torch.ones(2,3)

In [23]:
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [24]:
print(x.dtype)

torch.float32


In [25]:
x = torch.ones(2,3, dtype=torch.int)

In [26]:
print(x.dtype)

torch.int32


In [29]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.7673, 0.3035],
        [0.3076, 0.2326]])
tensor([[0.3310, 0.7607],
        [0.5048, 0.8829]])


In [31]:
z = x + y
z

tensor([[1.0983, 1.0642],
        [0.8124, 1.1155]])

In [32]:
y.add_(x)  # inplace operation that means just value change , is not create new tensor
print(y)

tensor([[1.0983, 1.0642],
        [0.8124, 1.1155]])


In [33]:
z = x * y
z = torch.mul(x,y)
z = torch.div(x,y)

In [34]:
x = torch.rand(5,3)
print(x)

tensor([[0.3298, 0.7081, 0.7206],
        [0.5490, 0.1189, 0.6643],
        [0.6668, 0.8408, 0.1880],
        [0.1129, 0.0561, 0.9324],
        [0.0663, 0.7165, 0.8602]])


In [46]:
print(x[1, :])

tensor([0.5490, 0.1189, 0.6643])


In [47]:
print(x[2, :])

tensor([0.6668, 0.8408, 0.1880])


In [48]:
print(x[1,1])

tensor(0.1189)


In [50]:
print(x[1,1].item())

0.11889439821243286


In [51]:
x = torch.rand(4,4)
print(x)

y = x.view(16)
print(y)

tensor([[0.7654, 0.5084, 0.8196, 0.4031],
        [0.1208, 0.9987, 0.1939, 0.0247],
        [0.8150, 0.5187, 0.3889, 0.4442],
        [0.8515, 0.4053, 0.5728, 0.1786]])
tensor([0.7654, 0.5084, 0.8196, 0.4031, 0.1208, 0.9987, 0.1939, 0.0247, 0.8150,
        0.5187, 0.3889, 0.4442, 0.8515, 0.4053, 0.5728, 0.1786])


In [52]:
import torch
import numpy as np



In [53]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [54]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [55]:
print(type(a))
print(type(b))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [57]:
a = np.ones(5)
c = torch.from_numpy(a)

In [58]:
print(a)


[1. 1. 1. 1. 1.]


In [59]:
print(c)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [60]:
a +=1
print(a)
print(b)

[2. 2. 2. 2. 2.]
[1. 1. 1. 1. 1.]


In [61]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device=device)
  y = torch.ones(5)
  y = y.to(device)
  z = x + y
  z = z.to("cpu")

In [62]:
x = torch.ones(4, requires_grad=True)
print(x)

tensor([1., 1., 1., 1.], requires_grad=True)
